// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Mason

import 'package:go_router/go_router.dart';
import 'package:data_entry/features/init/presentation/routes/init_route.dart' as init_route;
import 'package:data_entry/features/search_meter/presentation/routes/search_meter_route.dart' as search_meter_route;
import 'package:data_entry/features/home_page/presentation/routes/home_page_route.dart' as home_page_route;
import 'package:data_entry/features/sign_in/presentation/routes/sign_in_route.dart' as sign_in_route;
import 'package:data_entry/features/detail_meter/presentation/routes/detail_meter_route.dart' as detail_meter_route;
import 'package:data_entry/features/main_setup/presentation/routes/main_setup_route.dart' as main_setup_route;
import 'package:data_entry/features/meter_reading/presentation/routes/meter_reading_route.dart' as meter_reading_route;
import 'package:data_entry/features/add_customer/presentation/routes/add_customer_route.dart' as add_customer_route;
import 'package:data_entry/features/help/presentation/routes/help_route.dart' as help_route;

final List<RouteBase> allRoutes = [
  ...init_route.$appRoutes,
  ...search_meter_route.$appRoutes,
  ...home_page_route.$appRoutes,
  ...sign_in_route.$appRoutes,
  ...detail_meter_route.$appRoutes,
  ...main_setup_route.$appRoutes,
  ...meter_reading_route.$appRoutes,
  ...add_customer_route.$appRoutes,
  ...help_route.$appRoutes,
];
